
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Afganistán', true, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Albania', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Alemania', false, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Andorra', true, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Angola', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Barbuda', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Arabia Saudita', true, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Argelia', false, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Argentina', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Armenia', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Australia', true, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Austria', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Azerbaiyán', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Bahamas', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Bangladés', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Barbados', true, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Baréin', false, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Bélgica', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Belice', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Benín', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Bielorrusia', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Birmania', false, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Bolivia', true, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Bosnia y Herzegovina', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Botsuana', true, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Brasil', false, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Brunéi', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Bulgaria', true, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Burkina Faso', false, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Burundi', true, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Bután', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Cabo Verde', true, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Camboya', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Camerún', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Canadá', true, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Catar', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Chad', true, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Chile', true, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('China', false, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Chipre', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Colombia', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Comoras', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Corea del Norte', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Corea del Sur', true, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Costa de Marfil', false, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Costa Rica', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Croacia', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Cuba', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Dinamarca', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Dominica', true, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Ecuador', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Egipto', false, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('El Salvador', false, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Emiratos Árabes', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Eritrea', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Eslovaquia', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Eslovenia', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('España', true, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Estados Unidos', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Estonia', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Etiopía', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Filipinas', true, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Finlandia', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Fiyi', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Francia', true, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Gabón', true, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Gambia', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Georgia', false, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Ghana', true, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Granada', true, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Grecia', false, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Guatemala', true, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Guinea', true, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Guinea-Bisáu', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Guinea Ecuatorial', false, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Guyana', false, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Haití', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Honduras', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Hungría', true, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('India', false, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Indonesia', true, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Irak', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Irán', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Irlanda', true, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Islandia', false, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Islas Marshall', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Islas Salomón', false, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Israel', true, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Italia', false, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Jamaica', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Japón', true, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Jordania', true, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Kazajistán', true, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Kenia', false, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Kirguistán', false, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Kiribati', true, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Kuwait', false, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Laos', false, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Lesoto', true, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Letonia', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Líbano', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Liberia', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Libia', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Liechtenstein', false, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Lituania', true, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Luxemburgo', false, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Macedonia del Norte', true, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Madagascar', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Malasia', false, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Malaui', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Maldivas', true, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Malí', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Malta', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Marruecos', false, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Mauricio', false, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Mauritania', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('México', false, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Micronesia', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Moldavia', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Mónaco', false, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Mongolia', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Montenegro', true, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Mozambique', true, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Namibia', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Nauru', false, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Nepal', true, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Nicaragua', false, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Níger', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Nigeria', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Noruega', true, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Nueva Zelanda', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Omán', true, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Países Bajos', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Pakistán', false, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Palau', false, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Panamá', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Papúa Nueva Guinea', true, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Paraguay', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Perú', true, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Polonia', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Portugal', false, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Reino Unido', false, true, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('República Centroafricana', false, false, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('República Checa', false, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('República del Congo', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Congo', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('República Dominicana', false, true, true);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Ruanda', false, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Rumania', true, false, false);
insert into Pais (NombrePais, MedallaOro, MedallaPlata, MedallaBronce) values ('Rusia', false, false, false);


insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('9R19V34MX35', 'Afganistán', 'boxeo', 'Femenino', 'Darby', 'Kahan', 'Iglesia', '2000-12-16', '2024-08-01');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('2PX9N67FP01', 'Albania', 'golf', 'Masculino', 'Brett', 'Feander', 'O''Sheeryne', '2000-09-29', '2024-08-01');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('6G53DY3GN11', 'Alemania', 'maratón', 'Masculino', 'Ole', 'McCerery', 'Screeton', '2004-08-10', '2024-08-02');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('6MP9M66RM51', 'Andorra', 'rugby sevens', 'Femenino', 'Nady', 'Miskin', 'Aneley', '2000-12-06', '2024-07-28');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5F39JQ6KT05', 'Angola', 'bádminton', 'Femenino', 'Margette', 'Rimell', 'Illesley', '2004-07-17', '2024-08-07');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5W24JV0FM51', 'Barbuda', 'golf', 'Masculino', 'Patten', 'Brigden', 'Leyburn', '2004-12-21', '2024-07-28');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('1KE5TH3TU42', 'Arabia Saudita', 'escalada deportiva', 'Masculino', 'Hersch', 'Fildery', 'Holdin', '2001-09-03', '2024-07-26');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('3RF0EY7TR08', 'Argelia', 'natación artística', 'Masculino', 'Theobald', 'Ferby', 'Hedge', '1998-10-28', '2024-07-27');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('2Y18YE2RD60', 'Argentina', 'taekwondo', 'Masculino', 'Leon', 'Donoher', 'Mor', '1996-05-13', '2024-08-04');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('3WF0JG6GM88', 'Armenia', 'remo', 'Femenino', 'Shaina', 'Haughton', 'McConnulty', '1997-02-25', '2024-07-29');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('7JV0F21VJ26', 'Australia', 'golf', 'Femenino', 'Rosalinda', 'Leebeter', 'Borzoni', '1997-06-11', '2024-08-04');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('6TD9HN8TU82', 'Austria', 'natación', 'Masculino', 'Verney', 'Langston', 'Ivie', '2001-03-19', '2024-08-02');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5FP1H79XQ77', 'Azerbaiyán', 'tiro con arco', 'Masculino', 'Ari', 'Ianni', 'Jendas', '2003-05-29', '2024-07-29');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('8GC6HA6RH44', 'Bahamas', 'breaking', 'Femenino', 'Mattie', 'Hakonsson', 'Brimblecombe', '2003-09-10', '2024-07-30');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('2MW5TU0JX41', 'Bangladés', 'tenis de mesa', 'Masculino', 'Harlan', 'Munday', 'Rieger', '2000-08-07', '2024-07-30');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('3VA0P51JR49', 'Barbados', 'esgrima', 'Masculino', 'Danie', 'Tennet', 'Goding', '2000-08-16', '2024-08-06');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('9NN0KJ8HW44', 'Baréin', 'remo', 'Masculino', 'Shem', 'Studders', 'Belk', '2003-10-20', '2024-07-31');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('8QP6G88JP31', 'Bélgica', 'baloncesto', 'Femenino', 'Blondell', 'De Santos', 'Abrahams', '1999-02-17', '2024-08-01');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('8D36QC4CX83', 'Belice', 'tenis', 'Masculino', 'Ryley', 'O''Donnelly', 'Klees', '1999-10-25', '2024-08-06');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('1X11TR9XT53', 'Benín', 'vela', 'Femenino', 'Maryellen', 'McFarland', 'Jodlowski', '2004-12-19', '2024-08-02');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('6DT4XR5HU36', 'Bielorrusia', 'lucha grecorromana', 'Femenino', 'Zena', 'Swinden', 'Astlett', '1998-06-04', '2024-08-05');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('2AY8Y78KP61', 'Birmania', 'tiro con arco', 'Masculino', 'Thom', 'Weatherhill', 'Schwandermann', '1996-07-11', '2024-07-30');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('6XU5T80HM14', 'Bolivia', 'lucha grecorromana', 'Femenino', 'Maud', 'Ferrino', 'Pele', '2002-07-23', '2024-08-07');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('9KY1J42DG30', 'Bosnia y Herzegovina', 'saltos ecuestres', 'Masculino', 'Hiram', 'Levens', 'Merkel', '2004-01-11', '2024-08-10');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('6QW1QU3WG59', 'Botsuana', 'taekwondo', 'Femenino', 'Catlaina', 'Malser', 'Bahl', '2003-04-03', '2024-07-29');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('2X59JX0XM30', 'Brasil', 'maratón', 'Masculino', 'Godart', 'Coley', 'Pelosi', '2001-05-02', '2024-08-05');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('3F29AK4DD72', 'Brunéi', 'boxeo', 'Masculino', 'Lind', 'Lucchi', 'Bendix', '2003-08-03', '2024-07-27');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('2FT6NF9YG63', 'Bulgaria', 'esgrima', 'Femenino', 'Patience', 'Hallbird', 'Canning', '1997-03-22', '2024-08-06');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('1PP7N15WX99', 'Burkina Faso', 'judo', 'Masculino', 'Orv', 'Jacobsen', 'Cliff', '2004-11-22', '2024-08-06');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('3E17U56KN75', 'Burundi', 'patinaje', 'Masculino', 'Batholomew', 'Fidell', 'Ferrier', '2000-06-06', '2024-08-07');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5Y21P76HJ46', 'Bután', 'tiro', 'Masculino', 'Chase', 'Martyns', 'McCullagh', '1996-02-09', '2024-08-10');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('7G38NE8FW93', 'Cabo Verde', 'balonmano', 'Femenino', 'Bertina', 'Gussin', 'MacMenemy', '2001-11-11', '2024-08-06');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('4N66HN6AR10', 'Camboya', 'halterofilia', 'Femenino', 'Jacklin', 'Tapner', 'Gell', '1998-04-21', '2024-08-10');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('8YQ1P44HC49', 'Camerún', 'saltos de trampolín', 'Masculino', 'Gregorio', 'Yezafovich', 'Barszczewski', '1999-04-18', '2024-08-04');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('1VW3RQ2PK61', 'Canadá', 'tiro', 'Femenino', 'Arleen', 'Lapre', 'Carverhill', '2002-01-31', '2024-08-09');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5NN3P62PC50', 'Catar', 'gimnasia artística', 'Masculino', 'Clemente', 'Titford', 'Diment', '1998-08-24', '2024-08-08');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('6TP1TF2AA35', 'Chad', 'pentatlón moderno', 'Masculino', 'Corty', 'Faireclough', 'Kliement', '1997-04-06', '2024-08-10');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5TG4PN9JX59', 'Chile', 'tiro', 'Masculino', 'Quintin', 'Weine', 'Estabrook', '1996-09-12', '2024-07-30');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('4TE7GX5FD88', 'China', 'piragüismo en sprint', 'Masculino', 'Peadar', 'Stivers', 'Jauncey', '1998-06-18', '2024-08-03');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('1V45Y92YG80', 'Chipre', 'pentatlón moderno', 'Masculino', 'Ingar', 'Eckart', 'Gilleon', '2003-12-04', '2024-08-01');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5G48XG4CR61', 'Colombia', 'fútbol', 'Femenino', 'Agnola', 'Pavlenko', 'Pfiffer', '1995-02-18', '2024-07-26');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('8WQ1HE0EE47', 'Comoras', 'equitación', 'Femenino', 'Louise', 'Pilcher', 'Drinkhall', '1996-03-02', '2024-08-06');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('9N60RY2PQ66', 'Corea del Norte', 'gimnasia artística', 'Masculino', 'Fairleigh', 'Marrows', 'Prozescky', '2001-02-28', '2024-08-04');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('4DM7R24FN03', 'Corea del Sur', 'saltos ecuestres', 'Masculino', 'Rufe', 'Greenslade', 'Roback', '2003-12-16', '2024-08-02');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('3VH2Y18WU64', 'Costa de Marfil', 'piragüismo en eslalon', 'Femenino', 'Lind', 'Joinsey', 'Consterdine', '2001-12-09', '2024-08-03');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('3AQ9XR9XC35', 'Costa Rica', 'pentatlón moderno', 'Femenino', 'Kristal', 'Heinke', 'Bransden', '1995-07-25', '2024-08-01');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('2Y93JP8UC78', 'Croacia', 'saltos ecuestres', 'Masculino', 'Alexio', 'Moisey', 'Immins', '2002-02-14', '2024-08-05');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('2EQ2WQ6RN25', 'Cuba', 'pentatlón moderno', 'Femenino', 'Teresina', 'Ricco', 'Blyde', '1995-07-14', '2024-08-09');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('7TY1GT2EP66', 'Dinamarca', 'fútbol', 'Femenino', 'Salome', 'Murrhardt', 'Magwood', '2003-11-27', '2024-07-30');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('1JX7T69RY47', 'Dominica', 'escalada deportiva', 'Femenino', 'Rhiamon', 'Smickle', 'Ellingford', '1996-03-10', '2024-07-28');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('1MM9CJ3DF27', 'Ecuador', 'breaking', 'Femenino', 'Eleanor', 'Cahalan', 'Cobleigh', '1999-05-19', '2024-07-26');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('1HE6YG8QK53', 'Egipto', 'piragüismo en eslalon', 'Masculino', 'Maximilianus', 'Flaws', 'Vickress', '2001-07-10', '2024-08-06');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('8V03MX6KP24', 'El Salvador', 'BMX Freestyle', 'Masculino', 'Gordie', 'Sonier', 'Feather', '2002-11-04', '2024-08-06');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('2ED0HW8MJ41', 'Emiratos Árabes', 'boxeo', 'Femenino', 'Allis', 'McGettigan', 'Faichney', '2001-12-13', '2024-08-07');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('9A80NE9ND40', 'Eritrea', 'rugby sevens', 'Femenino', 'Gabriela', 'Spires', 'Reynish', '1999-01-06', '2024-08-07');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('6TC4W37CR57', 'Eslovaquia', 'natación', 'Femenino', 'Clarisse', 'O''Halligan', 'Batrim', '1995-10-04', '2024-07-26');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('2FF5D14KR55', 'Eslovenia', 'vela', 'Femenino', 'Hermia', 'Nice', 'Gregolotti', '2002-07-15', '2024-08-10');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('1CW4V75CG16', 'España', 'remo', 'Masculino', 'Goober', 'Horche', 'Gentric', '1997-01-22', '2024-07-26');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('4U62KF4UV47', 'Estados Unidos', 'natación artística', 'Femenino', 'Ursuline', 'Plows', 'Jaulmes', '2004-05-27', '2024-07-29');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('4GR0TT1AW99', 'Estonia', 'tenis', 'Femenino', 'Sherie', 'Jowle', 'Odell', '1996-10-14', '2024-07-31');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('9CE8Q47UD83', 'Etiopía', 'triatlón', 'Masculino', 'Feodor', 'Rixon', 'Barkworth', '2000-07-14', '2024-08-10');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('2CF8D54CH94', 'Filipinas', 'surf', 'Masculino', 'Ruperto', 'Deal', 'Kemish', '2002-01-05', '2024-08-03');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('3MG1M59UU93', 'Finlandia', 'golf', 'Femenino', 'Gerty', 'McRory', 'Allder', '2000-01-26', '2024-08-09');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5W97N62AJ22', 'Fiyi', 'remo', 'Masculino', 'Ly', 'Renahan', 'Poveleye', '2000-05-11', '2024-08-10');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('1JW4NR2XW29', 'Francia', 'BMX Racing', 'Masculino', 'Kristoforo', 'Gerdes', 'Atherley', '1999-07-28', '2024-08-09');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('8G72J28RY19', 'Gabón', 'ciclismo de montaña', 'Femenino', 'Cristy', 'Frazer', 'Brimley', '1997-04-30', '2024-08-05');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('4FJ2EA6PE32', 'Gambia', 'remo', 'Masculino', 'Sheppard', 'Symington', 'Arlett', '1997-05-12', '2024-08-09');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5N39NE6WY02', 'Georgia', 'triatlón', 'Femenino', 'Florette', 'Imore', 'Arminger', '2001-05-14', '2024-07-28');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('8KT7U73AQ52', 'Ghana', 'natación', 'Masculino', 'Uriah', 'Patron', 'Discombe', '1996-11-05', '2024-08-08');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('4EV6CU3MM51', 'Granada', 'baloncesto 3x3', 'Masculino', 'Horacio', 'Licciardo', 'Janku', '2004-02-16', '2024-08-07');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5PQ6XK1JE81', 'Grecia', 'ciclismo de ruta', 'Femenino', 'Jacquelyn', 'Creggan', 'Greenalf', '1996-01-16', '2024-08-10');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('7J82C51EM47', 'Guatemala', 'voleibol', 'Femenino', 'Sisely', 'Findon', 'Degg', '2000-07-08', '2024-08-06');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('2AJ2RP1JM72', 'Guinea', 'tenis', 'Masculino', 'Brock', 'Meineck', 'Boodle', '2000-04-14', '2024-08-06');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('1AG3MC0NM10', 'Guinea-Bisáu', 'boxeo', 'Femenino', 'Emylee', 'Vakhonin', 'De Matteis', '2002-09-19', '2024-08-07');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('8QN8CW8KF07', 'Guinea Ecuatorial', 'ciclismo de ruta', 'Femenino', 'Aeriell', 'Aldred', 'Vlahos', '2002-12-27', '2024-07-27');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('6W07D26CU70', 'Guyana', 'voleibol de playa', 'Femenino', 'Paula', 'Fullagar', 'Long', '2003-04-12', '2024-08-04');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('9Y24JJ6VU12', 'Haití', 'taekwondo', 'Masculino', 'Abie', 'Begwell', 'Brear', '2004-04-08', '2024-07-26');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('6T16N06AG01', 'Honduras', 'taekwondo', 'Masculino', 'Raleigh', 'Robinet', 'Gibbe', '1998-04-17', '2024-08-07');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('2FE4RT7VP67', 'Hungría', 'voleibol', 'Masculino', 'Bobby', 'Stearley', 'Rambaut', '2002-04-18', '2024-07-29');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('6MK1CD2KM79', 'India', 'BMX Racing', 'Masculino', 'Bank', 'Lujan', 'Lehrian', '1996-05-28', '2024-08-03');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('6P32G23PU30', 'Indonesia', 'bádminton', 'Femenino', 'Toby', 'Maskelyne', 'Dallman', '2004-01-22', '2024-08-03');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5JN6RR1QP08', 'Irak', 'golf', 'Masculino', 'Hewet', 'Carson', 'Howland', '1997-12-30', '2024-08-07');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('7J31FU1HP92', 'Irán', 'remo', 'Femenino', 'Kessia', 'Cruddas', 'Blandamere', '1996-10-20', '2024-08-10');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('9WJ0U89RP67', 'Irlanda', 'esgrima', 'Femenino', 'Orelia', 'Ible', 'Sauter', '1995-09-18', '2024-07-27');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('9DX3M60VC07', 'Islandia', 'saltos de trampolín', 'Masculino', 'Tomaso', 'Hackforth', 'Tafani', '2004-02-20', '2024-07-31');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('1QU5P72XF90', 'Islas Marshall', 'vela', 'Masculino', 'Ulberto', 'Wakeman', 'Runnett', '2001-06-03', '2024-08-05');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('7HC0TA5WD49', 'Islas Salomón', 'surf', 'Masculino', 'Gerald', 'Proud', 'Ivanchov', '2003-09-19', '2024-08-02');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('8DK5HX5HV75', 'Israel', 'taekwondo', 'Femenino', 'Nerte', 'Glisenan', 'Gadesby', '1997-03-09', '2024-08-02');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5PV4T84MC10', 'Italia', 'tenis de mesa', 'Masculino', 'Baudoin', 'Broomhead', 'Desbrow', '2001-03-07', '2024-08-07');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5HR6TD7VJ59', 'Jamaica', 'baloncesto', 'Masculino', 'Bordie', 'Woodyer', 'Pietrzyk', '1999-05-26', '2024-07-29');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('7CR0GT1RY62', 'Japón', 'halterofilia', 'Femenino', 'Dionis', 'Iddison', 'Coombs', '1998-03-31', '2024-08-04');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('7TA4FM9ET73', 'Jordania', 'tenis', 'Femenino', 'Alika', 'Berzin', 'Bohan', '2001-12-10', '2024-08-09');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('8ME8CD7MF19', 'Kazajistán', 'tiro', 'Masculino', 'Freddy', 'Doy', 'Fernanando', '2003-03-23', '2024-08-03');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('3XK8ND1QT39', 'Kenia', 'surf', 'Femenino', 'Caren', 'Orts', 'Keeves', '2000-07-17', '2024-08-07');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('8VY7VM8GR51', 'Kirguistán', 'equitación', 'Masculino', 'Arel', 'Ney', 'Baish', '1996-01-07', '2024-07-31');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('2H36Q90EE32', 'Kiribati', 'ciclismo de montaña', 'Masculino', 'Moises', 'Varty', 'Dietsche', '2003-11-28', '2024-08-02');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5JK7C91QP78', 'Kuwait', 'BMX Freestyle', 'Masculino', 'Iain', 'Rankling', 'Howat', '2004-02-04', '2024-07-27');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5WM1TG7PJ86', 'Laos', 'doma', 'Masculino', 'Tadeas', 'Halleday', 'Kyndred', '2001-06-05', '2024-07-27');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('4CW0AE4XW86', 'Lesoto', 'baloncesto 3x3', 'Femenino', 'Jennee', 'Broadberrie', 'Prandini', '2000-05-16', '2024-08-05');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('3J38HP8EM27', 'Letonia', 'BMX Racing', 'Femenino', 'Jermaine', 'Harberer', 'Barensen', '2003-06-27', '2024-08-04');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('9CY8H56CK68', 'Líbano', 'escalada deportiva', 'Femenino', 'Delilah', 'Kebbell', 'Dobson', '1996-12-04', '2024-08-09');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('6UR3XF0JA58', 'Liberia', 'gimnasia rítmica', 'Femenino', 'Stoddard', 'Baldery', 'Roome', '2001-10-12', '2024-08-03');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('4GH4N09HP12', 'Libia', 'bádminton', 'Masculino', 'Arlin', 'Elfes', 'Josefson', '1999-10-22', '2024-07-28');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('4HX2UX1HR29', 'Liechtenstein', 'escalada deportiva', 'Femenino', 'Arlyn', 'Riddle', 'Ransbury', '2000-12-19', '2024-08-07');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('6F71C78DT92', 'Lituania', 'piragüismo en sprint', 'Femenino', 'Carleen', 'Pinnock', 'Hopewell', '2001-03-25', '2024-08-07');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('2M31UQ1JA38', 'Luxemburgo', 'atletismo', 'Femenino', 'Karina', 'Grieve', 'Pampling', '1998-08-30', '2024-07-26');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('4EK3E46NX47', 'Macedonia del Norte', 'doma', 'Masculino', 'Baryram', 'Kiehl', 'Spiers', '1995-12-09', '2024-07-30');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('1XH1GJ5FJ67', 'Madagascar', 'doma', 'Masculino', 'Lannie', 'McConnulty', 'Lacer', '2003-07-01', '2024-07-28');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('8RX2K76AF78', 'Malasia', 'tenis de mesa', 'Femenino', 'Jamima', 'Fairs', 'Phillpot', '2002-04-27', '2024-07-28');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5UG5YC0RP04', 'Malaui', 'esgrima', 'Masculino', 'Lenci', 'Tillard', 'Richen', '2001-08-02', '2024-08-09');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('4QX0E95XA07', 'Maldivas', 'piragüismo en eslalon', 'Masculino', 'Zacharia', 'Mushart', 'Vertey', '2004-01-29', '2024-08-06');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('8M69CV8FA52', 'Malí', 'boxeo', 'Femenino', 'Susanna', 'Ysson', 'Elgey', '1997-09-18', '2024-07-28');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5PQ7AQ3RA34', 'Malta', 'esgrima', 'Masculino', 'Thorn', 'Weal', 'Slimm', '2000-05-10', '2024-08-04');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('9FJ5NF5FQ35', 'Marruecos', 'doma', 'Femenino', 'Evangelia', 'Gleave', 'Gianolo', '1998-10-24', '2024-07-29');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('9PG2WK6HF97', 'Mauricio', 'gimnasia artística', 'Masculino', 'Reginauld', 'MacGown', 'De Metz', '1998-06-30', '2024-08-03');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('2FA8GM6VA29', 'Mauritania', 'lucha grecorromana', 'Masculino', 'Rolph', 'Corless', 'Carass', '2001-05-23', '2024-07-30');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5TD9W61WX21', 'México', 'halterofilia', 'Masculino', 'Hirsch', 'Brundell', 'Ault', '2003-02-25', '2024-08-08');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('2J77J05VP48', 'Micronesia', 'saltos de trampolín', 'Masculino', 'Derron', 'Zealander', 'Stannas', '1999-05-10', '2024-08-06');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('7M52Y14EF72', 'Moldavia', 'waterpolo', 'Femenino', 'Bee', 'Coughlin', 'Peppett', '1999-03-24', '2024-08-08');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5WU4G50QH84', 'Mónaco', 'voleibol de playa', 'Femenino', 'Marin', 'Everest', 'Vye', '2001-01-11', '2024-07-31');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('8Q38TY7HT70', 'Mongolia', 'breaking', 'Femenino', 'Erma', 'Fforde', 'Liggens', '1995-10-05', '2024-08-07');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('3TX6DF7KY90', 'Montenegro', 'fútbol', 'Masculino', 'Antons', 'Hampshaw', 'Dourin', '1995-08-07', '2024-08-01');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('6TK7X44MU99', 'Mozambique', 'ciclismo de ruta', 'Masculino', 'Stillmann', 'Hrus', 'Norbury', '1996-06-26', '2024-08-08');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('2JK8N98RJ44', 'Namibia', 'gimnasia rítmica', 'Femenino', 'Dorrie', 'Viccary', 'Wynrehame', '1999-10-06', '2024-08-10');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('6F57PA4DY41', 'Nauru', 'esgrima', 'Femenino', 'Tracy', 'Pioch', 'Shardlow', '1997-10-27', '2024-07-26');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('1YQ6PY5XH23', 'Nepal', 'baloncesto', 'Femenino', 'Lesley', 'Siberry', 'Safhill', '2004-04-22', '2024-08-08');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('3W82MD2JE36', 'Nicaragua', 'ciclismo de ruta', 'Femenino', 'Georgianna', 'Gero', 'Defond', '1998-09-04', '2024-08-03');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('1V53UT1HY98', 'Níger', 'surf', 'Masculino', 'Waldon', 'Kondrat', 'Matias', '1995-11-07', '2024-08-03');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('9QK8JW9PA63', 'Nigeria', 'piragüismo en eslalon', 'Masculino', 'Mathe', 'Le Gassick', 'Fremantle', '1999-04-03', '2024-08-10');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('1M67J66MQ51', 'Noruega', 'BMX Racing', 'Femenino', 'Caressa', 'Fenty', 'Hyam', '2004-02-07', '2024-07-31');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('8H17F56AM53', 'Nueva Zelanda', 'vela', 'Femenino', 'Tory', 'Agnew', 'Kennon', '1998-08-22', '2024-08-04');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('7GX5QG4YE66', 'Omán', 'escalada deportiva', 'Femenino', 'Dinah', 'Siege', 'Amorine', '2004-06-01', '2024-08-03');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5T97C16PJ37', 'Países Bajos', 'BMX Freestyle', 'Masculino', 'Milty', 'Treadaway', 'Sherrum', '1996-07-15', '2024-08-07');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('7YK2KR0PX82', 'Pakistán', 'triatlón', 'Masculino', 'Nevin', 'Rides', 'Abilowitz', '1999-05-15', '2024-08-07');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('7ND3UA4HF71', 'Palau', 'remo', 'Femenino', 'Amie', 'Bosnell', 'Dohmann', '2002-10-06', '2024-07-28');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('8KT3FJ0XN61', 'Panamá', 'judo', 'Masculino', 'Rube', 'Zuker', 'Tukely', '1998-06-23', '2024-07-28');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('8YN8NX8PD91', 'Papúa Nueva Guinea', 'ciclismo de montaña', 'Femenino', 'Darline', 'Scatchard', 'Cockitt', '2002-05-07', '2024-07-26');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('2J47Q90HK96', 'Paraguay', 'lucha grecorromana', 'Masculino', 'Burlie', 'Olle', 'Jursch', '1998-08-20', '2024-08-09');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('3N37CF3HT45', 'Perú', 'remo', 'Femenino', 'Wally', 'Ferry', 'Jopson', '2004-04-21', '2024-08-03');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('7YV2U32UK45', 'Polonia', 'surf', 'Masculino', 'Hewie', 'Grosvenor', 'Winspeare', '2001-10-31', '2024-07-27');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('9GK5RG5QJ73', 'Portugal', 'piragüismo en eslalon', 'Femenino', 'Sybila', 'Harbertson', 'Howson', '2004-05-28', '2024-07-31');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('3GG7N44ME79', 'Reino Unido', 'tiro', 'Femenino', 'Arlie', 'Cammacke', 'Frampton', '1995-09-08', '2024-08-04');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('8GP5WF9YE62', 'República Centroafricana', 'patinaje', 'Masculino', 'Mitchell', 'Clemente', 'Kira', '1999-04-19', '2024-07-28');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('8F13KF4GC78', 'República Checa', 'escalada deportiva', 'Femenino', 'Raye', 'Treuge', 'Duchesne', '2003-07-29', '2024-07-26');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('7Q91C83WN78', 'República del Congo', 'BMX Racing', 'Masculino', 'Orazio', 'Gyles', 'Cutchey', '2000-11-22', '2024-07-28');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5CN2A63TF19', 'Congo', 'baloncesto 3x3', 'Femenino', 'Maggi', 'Gallally', 'Schoolfield', '2004-02-09', '2024-08-03');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('2R14VQ6QV74', 'República Dominicana', 'gimnasia rítmica', 'Femenino', 'Julianna', 'Cahalin', 'Ninotti', '2002-12-04', '2024-07-30');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('4NV2EK4JH68', 'Ruanda', 'tiro con arco', 'Masculino', 'Gherardo', 'McVee', 'Helbeck', '1999-09-12', '2024-08-08');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5KH9D35QK39', 'Rumania', 'natación', 'Masculino', 'Ashbey', 'Lenin', 'Shippam', '1999-06-10', '2024-07-29');
insert into Atleta (idAtleta, NombrePais, Disciplina, Genero, Nombre, ApellidoP, ApellidoM, FechaDeNacimiento, Año) values ('5PM5PA3HQ31', 'Rusia', 'vela', 'Femenino', 'Zelda', 'Kiezler', 'Garner', '1997-04-12', '2024-07-28');
